apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhaiis
  namespace: comparison
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rhaiis
  template:
    metadata:
      labels:
        name: rhaiis
    spec:
      containers:
        - name: rhaiis
          image: "registry.redhat.io/rhaiis/vllm-cuda-rhel9:3.2.0-1754088865-hotfix-1"
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: [
            "vllm serve meta-llama/Llama-3.3-70B-Instruct --tensor-parallel-size 4 --disable-log-requests"
          ]
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "16"
              memory: 128Gi
              nvidia.com/gpu: 4
            requests:
              cpu: "16"
              memory: 128Gi
              nvidia.com/gpu: 4
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
          env:
            - name: HF_HUB_OFFLINE
              value: "0"
            - name: HF_HUB_DISABLE_XET
              value: "1"
            - name: HF_HUB_ENABLE_HF_TRANSFER
              value: "0"
            - name: TRITON_LIBCUDA_PATH
              value: "/usr/lib64"
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token-secret
                  key: token
      imagePullSecrets:
        - name: 11009103-robshaw-token-pull-secret
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "16Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: rhaiis
  namespace: comparison
spec:
  type: ClusterIP
  selector:
    name: rhaiis
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
